baseURL = 'https://tmcdigitech.github.io/pgz/'
languageCode = 'en-au'
title = 'TMC - Pygame Zero'
theme = ["hugo-geekdoc", "reveal-hugo"]

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
# pygmentsCodeFences = true
disablePathToLower = true

publishDir = "docs"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true