baseURL = 'https://tmcdigitech.github.io/dit7/'
languageCode = 'en-au'
title = 'TMC - 7 Digital Tech'
theme = ["hugo-geekdoc", "reveal-hugo"]

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
# pygmentsCodeFences = true
disablePathToLower = true

[params]
geekdocCollapseAllSections = true

publishDir = "docs"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.goldmark.renderer]
unsafe = true
